/**
 * /api/driver/quotes
 *
 * GET   — return all quotes generated by the authenticated driver, newest first.
 * PATCH — set or clear the `won` flag on a specific quote owned by the caller.
 *
 * Both routes are scoped to the JWT caller's email — a driver can only read
 * and update their own quotes.
 *
 * PATCH body: { quoteId: string, won: boolean }
 */

import redis from '../_lib/redis.js'
import { verifyToken } from '../_lib/auth.js'

export default async function handler(req, res) {
  // ── Auth ──────────────────────────────────────────────────────────────────
  let caller
  try {
    caller = verifyToken(req)
  } catch (e) {
    return res.status(e.status ?? 401).json({ error: e.message })
  }

  const email = caller.email?.toLowerCase().trim()
  if (!email) return res.status(401).json({ error: 'Token missing email claim' })

  // ── GET — list all quotes for this driver ─────────────────────────────────
  if (req.method === 'GET') {
    try {
      // quotes:driver:{email} is an LPUSH list — index 0 is newest
      const allIds = await redis.lrange(`quotes:driver:${email}`, 0, -1)

      if (!allIds.length) {
        return res.status(200).json({ quotes: [] })
      }

      const raw    = await redis.mget(...allIds.map(id => `quote:${id}`))
      const quotes = raw.filter(Boolean)   // drop any null (orphaned IDs)

      return res.status(200).json({ quotes })
    } catch (e) {
      console.error('[driver/quotes GET]', e)
      return res.status(502).json({ error: 'Database error' })
    }
  }

  // ── PATCH — toggle won flag ────────────────────────────────────────────────
  if (req.method === 'PATCH') {
    const { quoteId, won } = req.body ?? {}

    if (!quoteId || typeof quoteId !== 'string') {
      return res.status(400).json({ error: '`quoteId` is required' })
    }
    if (typeof won !== 'boolean') {
      return res.status(400).json({ error: '`won` must be a boolean' })
    }

    let quote
    try {
      quote = await redis.get(`quote:${quoteId}`)
    } catch (e) {
      console.error('[driver/quotes PATCH] redis get error:', e)
      return res.status(502).json({ error: 'Database error' })
    }

    if (!quote) {
      return res.status(404).json({ error: `Quote ${quoteId} not found` })
    }

    // Enforce ownership — driver can only update their own quotes
    if (quote.driver?.email?.toLowerCase() !== email) {
      return res.status(403).json({ error: 'You do not have permission to update this quote' })
    }

    const updated = { ...quote, won }

    try {
      await redis.set(`quote:${quoteId}`, updated)
    } catch (e) {
      console.error('[driver/quotes PATCH] redis set error:', e)
      return res.status(502).json({ error: 'Database error' })
    }

    console.log(`[driver/quotes] ${email} marked ${quoteId} won=${won}`)
    return res.status(200).json({ quote: updated })
  }

  return res.status(405).json({ error: 'Method not allowed' })
}
