/**
 * /api/driver/quotes
 *
 * GET   — return all quotes generated by the authenticated driver, newest first.
 * PATCH — set or clear the `won` flag on a specific quote owned by the caller.
 *
 * Both routes are scoped to the JWT caller's email — a driver can only read
 * and update their own quotes.
 *
 * PATCH body: { quoteId: string, won: boolean }
 */

import redis              from '../_lib/redis.js'
import { requireAuth }   from '../_lib/auth.js'
import { k }             from '../_lib/keys.js'
import { setSecurityHeaders } from '../_lib/headers.js'

export default async function handler(req, res) {
  setSecurityHeaders(res)

  // ── Auth: checks active flag and token-invalidation-after-pw-change ──────────
  const caller = await requireAuth(req, res)
  if (!caller) return

  const email = caller.email?.toLowerCase().trim()
  if (!email) return res.status(401).json({ error: 'Token missing email claim' })

  // ── GET — list all quotes for this driver ─────────────────────────────────
  if (req.method === 'GET') {
    try {
      const allIds = await redis.lrange(k.quotesDriver(email), 0, -1)

      if (!allIds.length) {
        return res.status(200).json({ quotes: [] })
      }

      const raw    = await redis.mget(...allIds.map(id => k.quote(id)))
      const quotes = raw.filter(Boolean)

      return res.status(200).json({ quotes })
    } catch (e) {
      console.error('[driver/quotes GET]', e)
      return res.status(502).json({ error: 'Database error' })
    }
  }

  // ── PATCH — toggle won flag ────────────────────────────────────────────────
  if (req.method === 'PATCH') {
    const { quoteId, won } = req.body ?? {}

    if (!quoteId || typeof quoteId !== 'string') {
      return res.status(400).json({ error: '`quoteId` is required' })
    }
    if (typeof won !== 'boolean') {
      return res.status(400).json({ error: '`won` must be a boolean' })
    }

    let quote
    try {
      quote = await redis.get(k.quote(quoteId))
    } catch (e) {
      console.error('[driver/quotes PATCH] redis get error:', e)
      return res.status(502).json({ error: 'Database error' })
    }

    if (!quote) {
      return res.status(404).json({ error: `Quote ${quoteId} not found` })
    }

    // Enforce ownership — driver can only update their own quotes
    if (quote.driver?.email?.toLowerCase() !== email) {
      return res.status(403).json({ error: 'You do not have permission to update this quote' })
    }

    const updated = { ...quote, won }

    try {
      await redis.set(k.quote(quoteId), updated)
    } catch (e) {
      console.error('[driver/quotes PATCH] redis set error:', e)
      return res.status(502).json({ error: 'Database error' })
    }

    console.log(`[driver/quotes] ${email} marked ${quoteId} won=${won}`)
    return res.status(200).json({ quote: updated })
  }

  return res.status(405).json({ error: 'Method not allowed' })
}
