/**
 * GET /api/admin/drivers/quotes?email=...&page=1
 *
 * Auth: Admin JWT
 *
 * Returns a paginated list of quotes generated by the given driver.
 * Quote snapshots are written to Redis by api/quote.js on every generation.
 */

import redis from '../../_lib/redis.js'
import { requireAdmin } from '../../_lib/auth.js'

const PAGE_SIZE = 15

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const admin = requireAdmin(req, res)
  if (!admin) return

  const { email, page: pageStr = '1' } = req.query ?? {}

  if (!email || typeof email !== 'string' || !email.trim()) {
    return res.status(400).json({ error: '`email` query param is required' })
  }

  const normalizedEmail = email.toLowerCase().trim()
  const page            = Math.max(1, parseInt(pageStr, 10) || 1)

  try {
    // LPUSH order: index 0 is the newest quote ID
    const allIds = await redis.lrange(`quotes:driver:${normalizedEmail}`, 0, -1)
    const total  = allIds.length

    if (total === 0) {
      return res.status(200).json({ quotes: [], total: 0, page: 1, totalPages: 1 })
    }

    const totalPages = Math.ceil(total / PAGE_SIZE)
    const safePage   = Math.min(page, totalPages)
    const start      = (safePage - 1) * PAGE_SIZE
    const pageIds    = allIds.slice(start, start + PAGE_SIZE)

    const raw    = await redis.mget(...pageIds.map(id => `quote:${id}`))
    const quotes = raw.filter(Boolean)

    return res.status(200).json({ quotes, total, page: safePage, totalPages })
  } catch (e) {
    console.error('[driver-quotes]', e)
    return res.status(502).json({ error: 'Database error' })
  }
}
